"""Update users table

Revision ID: 177b36f0bff9
Revises: e0e768f2d582
Create Date: 2026-05-25 17:54:26.725725

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '177b36f0bff9'
down_revision = 'e0e768f2d582'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('voter_application_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('voter_id', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('full_name', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.drop_index(batch_op.f('username'))
        batch_op.create_unique_constraint(None, ['voter_id'])
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.create_foreign_key(None, 'voter_applications', ['voter_application_id'], ['id'])
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', mysql.VARCHAR(length=100), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('username'), ['username'], unique=True)
        batch_op.drop_column('created_at')
        batch_op.drop_column('email')
        batch_op.drop_column('full_name')
        batch_op.drop_column('voter_id')
        batch_op.drop_column('voter_application_id')

    # ### end Alembic commands ###
