"""Added election management system

Revision ID: 3f73792d1c23
Revises: eff2ff25cd4f
Create Date: 2026-05-29 18:53:50.673295

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3f73792d1c23'
down_revision = 'eff2ff25cd4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('election_votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('election_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('voter_id', sa.Integer(), nullable=False),
    sa.Column('voted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['election_id'], ['elections.id'], ),
    sa.ForeignKeyConstraint(['voter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('votes')
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manifesto', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('photo', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('verified_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('party_name',
               existing_type=mysql.VARCHAR(length=150),
               nullable=True)
        batch_op.create_foreign_key(None, 'users', ['verified_by'], ['id'])
        batch_op.drop_column('bio')
        batch_op.drop_column('symbol_image')
        batch_op.drop_column('constituency')
        batch_op.drop_column('vote_count')

    with op.batch_alter_table('elections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_date', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('end_date', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True))
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('election_type',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'])
        batch_op.drop_column('end_datetime')
        batch_op.drop_column('constituency')
        batch_op.drop_column('start_datetime')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('elections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_datetime', mysql.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('constituency', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('end_datetime', mysql.DATETIME(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('election_type',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.drop_column('created_by')
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')

    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vote_count', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('constituency', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('symbol_image', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('bio', mysql.TEXT(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('party_name',
               existing_type=mysql.VARCHAR(length=150),
               nullable=False)
        batch_op.drop_column('created_at')
        batch_op.drop_column('verified_by')
        batch_op.drop_column('status')
        batch_op.drop_column('photo')
        batch_op.drop_column('manifesto')

    op.create_table('votes',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('voter_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('candidate_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('election_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('voted_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], name=op.f('votes_ibfk_1')),
    sa.ForeignKeyConstraint(['election_id'], ['elections.id'], name=op.f('votes_ibfk_2')),
    sa.ForeignKeyConstraint(['voter_id'], ['users.id'], name=op.f('votes_ibfk_3')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('election_votes')
    # ### end Alembic commands ###
