"""Added department management system

Revision ID: 6cdf19f976e2
Revises: dbd03c750b12
Create Date: 2026-05-29 14:40:59.873368

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6cdf19f976e2'
down_revision = 'dbd03c750b12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('department_officers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('designation', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('assigned_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('joined_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('role',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.drop_index(batch_op.f('email'))
        batch_op.create_foreign_key(None, 'users', ['assigned_by'], ['id'])
        batch_op.create_foreign_key(None, 'departments', ['department_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('password_hash')
        batch_op.drop_column('is_active')
        batch_op.drop_column('department_name')
        batch_op.drop_column('full_name')
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('department_officers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', mysql.VARCHAR(length=120), nullable=False))
        batch_op.add_column(sa.Column('full_name', mysql.VARCHAR(length=150), nullable=False))
        batch_op.add_column(sa.Column('department_name', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('password_hash', mysql.VARCHAR(length=255), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index(batch_op.f('email'), ['email'], unique=True)
        batch_op.alter_column('role',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('joined_at')
        batch_op.drop_column('assigned_by')
        batch_op.drop_column('designation')
        batch_op.drop_column('user_id')
        batch_op.drop_column('department_id')

    op.drop_table('departments')
    # ### end Alembic commands ###
