"""Phase 1 admin architecture

Revision ID: d53bce293238
Revises: 6cdf19f976e2
Create Date: 2026-05-29 18:05:55.546592

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd53bce293238'
down_revision = '6cdf19f976e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('from_department', sa.String(length=150), nullable=True),
    sa.Column('to_department', sa.String(length=150), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('performed_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['voter_applications.id'], ),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('department_officers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('voter_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('assigned_officer_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('workflow_status', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('risk_level', sa.String(length=50), nullable=True))
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=30),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'departments', ['department_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['assigned_officer_id'], ['id'])
        batch_op.drop_column('current_department')
        batch_op.drop_column('admin_reviewed_by')
        batch_op.drop_column('workflow_stage')
        batch_op.drop_column('forwarded_at')
        batch_op.drop_column('verified_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voter_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verified_at', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('forwarded_at', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('workflow_stage', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('admin_reviewed_by', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('current_department', mysql.VARCHAR(length=100), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('status',
               existing_type=sa.String(length=30),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.drop_column('risk_level')
        batch_op.drop_column('workflow_status')
        batch_op.drop_column('assigned_officer_id')
        batch_op.drop_column('department_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('last_login')
        batch_op.drop_column('status')

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('department_officers', schema=None) as batch_op:
        batch_op.drop_column('status')

    op.drop_table('workflow_logs')
    # ### end Alembic commands ###
