"""Make voter_application_id nullable

Revision ID: dbd03c750b12
Revises: 149f17b38809
Create Date: 2026-05-28 18:35:13.022031

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dbd03c750b12'
down_revision = '149f17b38809'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('voter_application_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('voter_application_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
